---
title: "Excavata_Project"
author: "Kyle Johnson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Include the libraries here
# Libraries
library(tidyverse)
library(rentrez)
library(ggrepel)
library(gridExtra)
library(plotly)
library(kableExtra)
```

```{r}
# Initalize the functions here
# Functions for filtering purposes and addition of information

Species_Name <- function(maincsv, namecsv){
  #First add the organism name column to the maincsv
  #Filling it with NA
  #Check to see if it has it already
  if ("Organism" %in% colnames(maincsv)){
  }else{
    maincsv <- maincsv %>% add_column(Organism=NA, .before = "tid")
  }
  #Iterate through the rows of the main csv file
  for (i in 1:nrow(maincsv)){
    #print(maincsv[i, "taxid"])
    
    #Iterate through the name csv file
    for (n in 1:nrow(namecsv)){
      if (maincsv[i, "taxid"] == namecsv[n, "Organism_Taxonomic_ID"]){
        #print(namecsv[n,"Organism"])
        maincsv$Organism[i] <- namecsv$Organism.Name[n]
      } else{
        next
      }
    }
  }
  return(maincsv) 
}

Taxon_Add <- function(csvToAdd){
  temp <- csvToAdd
  if("taxid" %in% colnames(temp)){
  }else{
    temp <- temp %>%
      add_column(taxid = NA, .before = "tar")
  }
    for (r in 1:nrow(temp)){
      print(r)
      targ <- temp[r, "tar"]
      eSearch <- entrez_search(db ="protein", term = targ)
      eSummary <- entrez_summary(db="protein", id=eSearch$ids)
      print(eSummary$taxid)
      if(is.null(eSummary$taxid)){
        next
      } else{}
      
      taxID <- extract_from_esummary(eSummary, "taxid")
      ID <- unname(taxID)
      if(nrow(temp) >0){
        temp$taxid[r] <- ID
      } else {}
    }
# Finally, return the value held within temp to the output of the function
  return(temp)
}

Check_Ciliates <- function (toBeCompared, ciliate){
  # Add in a column that will have values for comparing. Default is false
  # Adding the column after the Organism column (requires that it exists)
  if ("Ciliate_Check" %in% colnames(toBeCompared)){
  }else{
    toBeCompared <- toBeCompared %>%
      add_column(Ciliate_Check = FALSE, .after = "bid")
  }
  #print(toBeCompared)
  # Get rid of any spaces and replace them with _
  colnames(ciliate) = gsub(" ", "_", colnames(ciliate))
  #print(nrow(ciliate))
  #print(ciliate)
  
  # Iterate through the toBeCompared dataframe and the ciliates dataframe
  if(dim(toBeCompared)[1] == 0){
    return(toBeCompared)
  }else{
    for (n in 1:nrow(toBeCompared)){
      for(c in 1:nrow(ciliate)){
        if(toBeCompared[n, "Organism_Taxonomic_ID"] == ciliate[c, "Organism_Taxonomic_ID"]){
          toBeCompared$Ciliate_Check[n] <- TRUE
        }else{}
      }
  }
  return(toBeCompared)
  }
}

photoCheck <- function(inputCSV , photoCSV){
  if ("Has_D1" %in% colnames(inputCSV)){
  }else{
    inputCSV <- inputCSV %>% add_column(Has_D1 = FALSE, .after = "bid")
  }
  
  if(dim(inputCSV)[1] == 0){
    return(inputCSV)
  }else{
    for(n in 1:nrow(photoCSV)){
    #print("PhotoCSV Values")
    #print(photoCSV$Has_D1[n])
      for(m in 1:nrow(inputCSV)){
      #print("InputCSV Values")
      #print(inputCSV$Has_D1[m])
        if(inputCSV[m, "Organism_Taxonomic_ID"] == photoCSV[n,"Organism_Taxonomic_ID"]){
          inputCSV$Has_D1[m] <- TRUE
        }else{
        }
      }
    }
  #print(inputCSV$Has_D1)
    return(inputCSV)
  }
}

ComplexCheck2 <- function (inputdf, SIN1df, RICTORdf){
  # Check to see if the input function has the column already. Add it if it does not
  if ("TORC2" %in% colnames(inputdf)){
  }else{
    inputdf <- inputdf %>% add_column(TORC2 = FALSE, .after = "Organism.Name")
  }
  
  
  #Loop to iterate through the inputdf
  for (n in 1:nrow(inputdf)) {
    #Loop to iterate through the RICTORdf
    for (i in 1:nrow(RICTORdf)){
      #Loop to iterate through the SIN1df
      for (j in 1:nrow(SIN1df)){
        if (inputdf[n, "Organism_Taxonomic_ID"] == RICTORdf[i, "Organism_Taxonomic_ID"] & inputdf[n, "Organism_Taxonomic_ID"] == SIN1df[j, "Organism_Taxonomic_ID"]){
          inputdf$TORC2[n] <- TRUE
        }else{}
      }
    }
  }
  
  return(inputdf)
  
}

mainCombine <- function(Grouping, Namedf, RICTORdf, SIN1df, RAPTORdf, LST8df, TORdf, D1df){
  
  # Make the empty dataframe
  returnDf <- data.frame()
  
  # Add in the taxid and species names columns to the dataframe
  returnDF <- subset(Namedf, select = c("Accn","Organism_Taxonomic_ID", "Organism_Name"))
  
  # Now create empty columns and rows that will be filled in later in the function
  # These will be the "checking" sections for each of the specified proteins
  
  returnDF <- returnDF %>% add_column(SIN1 = NA, RICTOR = NA, RAPTOR = NA, TOR = NA, LST8 = NA, D1 = NA)
  returnDF <- returnDF %>% add_column(Phylum = Grouping, .before = "Accn")
  
  #Check the input dataframes to see if they are of length 0. If they are, do something about it
  
  
  if(nrow(RICTORdf) != 0){# First loop to check for RICTOR
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(RICTORdf)){
        #condition check to see if the taxIDs line up
        if(returnDF[n, "Organism_Taxonomic_ID"] == RICTORdf[m, "Organism_Taxonomic_ID"]){
          if (RICTORdf[m, "scd"] > 300){
          returnDF$RICTOR[n] <- "H"
          }else if (RICTORdf[m,"scd"] < 300 & RICTORdf[m,"scd"] > 150){
          returnDF$RICTOR[n] <- "M"
          }else if (RICTORdf[m,"scd"] < 150){
          returnDF$RICTOR[n] <- "L"
          }
        } else{
          next
        }
      }
      
    }
    print("Finished RICTOR")
  }else{}
    #Second Loop for SIN1
  if(nrow(SIN1df) != 0){
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(SIN1df)){
        #condition check to see if the taxIDs line up
        if(returnDF[n, "Organism_Taxonomic_ID"] == SIN1df[m, "Organism_Taxonomic_ID"]){
          if (SIN1df[m, "scd"] > 300){
          returnDF$SIN1[n] <- "H"
          }else if (SIN1df[m,"scd"] < 300 & SIN1df[m,"scd"] > 150){
          returnDF$SIN1[n] <- "M"
          }else if (SIN1df[m,"scd"] < 150){
          returnDF$SIN1[n] <- "L"
          }
        } else{
          next
        }
      }
      
    }
    print("Finished SIN1")
  }else{}

    #Third Loop for RAPTOR
  if(nrow(RAPTORdf) != 0){
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(RAPTORdf)){
        #condition check to see if the taxIDs line up
        if(returnDF[n, "Organism_Taxonomic_ID"] == RAPTORdf[m, "Organism_Taxonomic_ID"]){
          if (RAPTORdf[m, "scd"] > 300){
          returnDF$RAPTOR[n] <- "H"
          }else if (RAPTORdf[m,"scd"] < 300 & RAPTORdf[m,"scd"] > 150){
          returnDF$RAPTOR[n] <- "M"
          }else if (RAPTORdf[m,"scd"] < 150){
          returnDF$RAPTOR[n] <- "L"
          }
        } else{
          next
        }
      }
      
    }
    print("Finished RAPTOR")
  }else{}
  
  
    #Fourth Loop for LST8
  print(nrow(LST8df))
  if(nrow(LST8df) != 0){
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(LST8df)){
        #condition check to see if the taxIDs line up
        if(returnDF[n,"Organism_Taxonomic_ID"] == LST8df[m, "Organism_Taxonomic_ID"]){
          if (LST8df[m, "scd"] > 300){
          returnDF$LST8[n] <- "H"
          }else if (LST8df[m,"scd"] < 300 & LST8df[m,"scd"] > 150){
          returnDF$LST8[n] <- "M"
          }else if (LST8df[m,"scd"] < 150){
          returnDF$LST8[n] <- "L"
          }
        } else{
          next
        }
      }
    }
    print("Finished LST8")
  }else{}
  
    #Fourth Loop for TOR
  if(nrow(TORdf) != 0){
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(TORdf)){
        #condition check to see if the taxIDs line up
        if(returnDF[n, "Organism_Taxonomic_ID"] == TORdf[m, "Organism_Taxonomic_ID"]){
          if (TORdf[m, "scd"] > 300){
          returnDF$TOR[n] <- "H"
          }else if (TORdf[m,"scd"] < 300 & TORdf[m,"scd"] > 150){
          returnDF$TOR[n] <- "M"
          }else if (TORdf[m,"scd"] < 150){
          returnDF$TOR[n] <- "L"
          }
        } else{
          next
        }
      }
      
    }
  }else{}

  
      #Fifth Loop for D1
  if(nrow(D1df) != 0){
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(D1df)){
        #condition check to see if the taxIDs line up
        if(returnDF[n, "Organism_Taxonomic_ID"] == D1df[m, "Organism_Taxonomic_ID"]){
          if (D1df[m, "scd"] > 300){
          returnDF$D1[n] <- "H"
          }else if (D1df[m,"scd"] < 300 & D1df[m,"scd"] > 150){
          returnDF$D1[n] <- "M"
          }else if (D1df[m,"scd"] < 150){
          returnDF$D1[n] <- "L"
          }
        } else{
          next
        }
      }
      
    } 
  }else{}
  
  
# Finally return the completed dataframe   
return(returnDF)  
}

# Global Variables for Analysis

# Score Values
#LST8, RAPTOR, TOR
LRTScoreA <- 150
LRTScoreD <- 150

#RICTOR, SIN1, D1
RSDScoreA <- 100
RSDScoreD <- 100
```

```{r}
D1Discoba <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Discoba/D1_Discoba.csv")
LST8Discoba <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Discoba/LST8_Discoba.csv")
RICTORDiscoba <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Discoba/RICTOR_Discoba.csv")
RAPTORDiscoba <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Discoba/RAPTOR_Discoba.csv")
SIN1Discoba <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Discoba/SIN1_Discoba.csv")
TORDiscoba <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Discoba/TOR_Discoba.csv")
DiscobaNames <- read_tsv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Discoba/Discoba_Names.tsv", show_col_types = FALSE)
DiscobaNames <- DiscobaNames %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")

```

```{r}
Euglenozoa <- read_tsv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Discoba/Euglenozoa_Information.tsv", show_col_types = FALSE)
Euglenozoa <- Euglenozoa %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")
Heterolobosea <- read_tsv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Discoba/Heterolobosea_Information.tsv", show_col_types = FALSE)
Heterolobosea <- Heterolobosea %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")
Jakobida <- read_tsv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Discoba/Jakobida_Information.tsv", show_col_types = FALSE)
Jakobida <- Jakobida %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")
```

```{r}
Anaeramoebidae <- read_tsv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/Anaeramoebidae_Information.tsv", show_col_types = FALSE) %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")
Fornicata <- read_tsv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/Fornicata_Information.tsv", show_col_types = FALSE) %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")
Parabasalia <- read_tsv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/Parabasalia_Information.tsv", show_col_types = FALSE) %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")
Preaxostyla <- read_tsv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/Preaxostyla_Information.tsv", show_col_types = FALSE) %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")

```

```{r}
TaxonomyDiscoba <- read_tsv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Discoba/taxonomy_summary.tsv", show_col_types = FALSE) %>% rename(Organism_Taxonomic_ID = "Taxid")
TaxonomyMetamonada <- read_tsv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/taxonomy_summary.tsv", show_col_types = FALSE) %>% rename(Organism_Taxonomic_ID = "Taxid")
```




```{r}

D1Metamonada <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/D1_Metamonada.csv")
LST8Metamonada <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/LST8_Metamonada.csv")
RICTORMetamonada <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/RICTOR_Metamonada.csv")
RAPTORMetamonada <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/RAPTOR_Metamonada.csv")
SIN1Metamonada <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/SIN1_Metamonada.csv")
TORMetamonada <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/TOR_Metamonada.csv")
MetamonadaNames <- read_tsv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Updated_Metamonada/Metamonada_Names.tsv", show_col_types = FALSE)
MetamonadaNames <- MetamonadaNames %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")
```

```{r}
Excavata_Busco <- read.csv("~/GitHub/TOR_phylogenetics/GitHub_CSV/Excavata-BUSCO-Sheet1.csv", na = 0)
Excavata_Busco <- Excavata_Busco %>% rename(Accn = Accession)
Excavata_Busco$C.score <-gsub("%$","",Excavata_Busco$C.score)
Excavata_Busco$C.score <- as.numeric(as.character(Excavata_Busco$C.score))
Excavata_Busco$Frag.score <- gsub("%$", "", Excavata_Busco$Frag.score)
Excavata_Busco$Frag.score <- as.numeric(as.character(Excavata_Busco$Frag.score))
```


```{r}
D1Discoba <- merge(D1Discoba, DiscobaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
LST8Discoba <- merge(LST8Discoba, DiscobaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
RICTORDiscoba <- merge(RICTORDiscoba, DiscobaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
RAPTORDiscoba <- merge(RAPTORDiscoba, DiscobaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
SIN1Discoba <- merge(SIN1Discoba, DiscobaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
TORDiscoba <- merge(TORDiscoba, DiscobaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")

D1Metamonada <- merge(D1Metamonada, MetamonadaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
LST8Metamonada <- merge(LST8Metamonada, MetamonadaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
RICTORMetamonada <- merge(RICTORMetamonada, MetamonadaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
RAPTORMetamonada <- merge(RAPTORMetamonada, MetamonadaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
SIN1Metamonada <- merge(SIN1Metamonada, MetamonadaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
TORMetamonada <- merge(TORMetamonada, MetamonadaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")


```

```{r}
RICTORMetamonada <- merge(RICTORMetamonada, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
RAPTORMetamonada <- merge(RAPTORMetamonada, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
SIN1Metamonada <- merge(SIN1Metamonada, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
LST8Metamonada <- merge(LST8Metamonada, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
TORMetamonada <- merge(TORMetamonada, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
D1Metamonada <- merge(D1Metamonada, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")

RICTORDiscoba <- merge(RICTORDiscoba, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
RAPTORDiscoba <- merge(RAPTORDiscoba, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
SIN1Discoba <- merge(SIN1Discoba, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
LST8Discoba <- merge(LST8Discoba, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
TORDiscoba <- merge(TORDiscoba, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
D1Discoba <- merge(D1Discoba, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
```


```{r}
D1Discoba <- D1Discoba %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup

LST8Discoba <- LST8Discoba %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup

RICTORDiscoba <- RICTORDiscoba %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup

RAPTORDiscoba <- RAPTORDiscoba %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup

SIN1Discoba <- SIN1Discoba %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup

TORDiscoba <- TORDiscoba %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup

D1Metamonada <- D1Metamonada %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup

LST8Metamonada <- LST8Metamonada %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup

RICTORMetamonada <- RICTORMetamonada %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup

RAPTORMetamonada <- RAPTORMetamonada %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup

SIN1Metamonada <- SIN1Metamonada %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup

TORMetamonada <- TORMetamonada %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
```

```{r}
CombinedDiscoba <- mainCombine("Discoba", DiscobaNames, RICTORDiscoba, SIN1Discoba, RAPTORDiscoba, LST8Discoba, TORDiscoba, D1Discoba)
CombinedMetamonada <- mainCombine("Metamonada",MetamonadaNames, RICTORMetamonada, SIN1Metamonada, RAPTORMetamonada, LST8Metamonada, TORMetamonada, D1Metamonada)



CombinedDiscoba <- merge(CombinedDiscoba, Excavata_Busco[c("C.score","Frag.score", "Accn")], by = "Accn")
CombinedDiscoba <- CombinedDiscoba %>% left_join(select(TaxonomyDiscoba, `Class name`,`Phylum name`,`Order name`, `Family name`, `Genus name`, Organism_Taxonomic_ID), by=c("Organism_Taxonomic_ID"))

CombinedMetamonada <- merge(CombinedMetamonada, Excavata_Busco[c("C.score","Frag.score","Accn")], by = "Accn")
CombinedMetamonada <- CombinedMetamonada %>% left_join(select(TaxonomyMetamonada, `Class name`,`Phylum name`,`Order name`, `Family name`, `Genus name`, Organism_Taxonomic_ID), by=c("Organism_Taxonomic_ID"))

```


```{r}
write.csv(CombinedDiscoba, "~/GitHub/TOR_phylogenetics/GitHub_CSV/Combined_CSVs/CombinedDiscoba.csv")
write.csv(CombinedMetamonada,"~/GitHub/TOR_phylogenetics/GitHub_CSV/Combined_CSVs/CombinedMetamonada.csv")


```



```{r}
Dplot1 <- ggplot(RICTORDiscoba, aes(x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 30,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  ggtitle("RICTOR Discoba")
Dplot1

Mplot1 <- ggplot(RICTORMetamonada, aes(x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 30,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  ggtitle("RICTOR Metamonada")
Mplot1


```



```{r}
RICTORMetamonadaPlot <- ggplot(RICTORMetamonada, aes(x = sca, y = scd, color = C.score, label = Organism_Name))+
  geom_point()+
  geom_text_repel(data = RICTORMetamonada,
                  direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("RICTOR Hits Metamonada")

RICTORDiscobaPlot <- ggplot(RICTORDiscoba, aes(x = sca, y = scd, color = C.score, label = Organism_Name))+
  geom_point()+
  geom_text_repel(data = RICTORDiscoba,
                  direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("RICTOR Hits Discoba")


RAPTORMetamonadaPlot <- ggplot(RAPTORMetamonada, aes(x = sca, y = scd, color = C.score, label = Organism_Name))+
  geom_point()+
  geom_text_repel(data = RAPTORMetamonada,
                  direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("RAPTOR Hits Metamonada")

RAPTORDiscobaPlot <- ggplot(RAPTORDiscoba, aes(x = sca, y = scd, color = C.score, label = Organism_Name))+
  geom_point()+
  geom_text_repel(data = RAPTORDiscoba,
                  direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("RAPTOR Hits Discoba")


TORMetamonadaPlot <- ggplot(TORMetamonada, aes(x = sca, y = scd, color = C.score, label = Organism_Name))+
  geom_point()+
  geom_text_repel(data = TORMetamonada,
                  direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("TOR Hits Metamonada")

TORDiscobaPlot <- ggplot(TORDiscoba, aes(x = sca, y = scd, color = C.score, label = Organism_Name))+
  geom_point()+
  geom_text_repel(data = TORDiscoba,
                  direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("TOR Hits Discoba")

SIN1MetamonadaPlot <- ggplot(SIN1Metamonada, aes(x = sca, y = scd, color = C.score, label = Organism_Name))+
  geom_point()+
  geom_text_repel(data = SIN1Metamonada,
                  direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("SIN1 Hits Metamonada")

SIN1DiscobaPlot <- ggplot(SIN1Discoba, aes(x = sca, y = scd, color = C.score, label = Organism_Name))+
  geom_point()+
  geom_text_repel(data = SIN1Discoba,
                  direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("SIN1 Hits Discoba")


LST8MetamonadaPlot <- ggplot(LST8Metamonada, aes(x = sca, y = scd, color = C.score, label = Organism_Name))+
  geom_point()+
  geom_text_repel(data = LST8Metamonada,
                  direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("LST8 Hits Metamonada")

LST8DiscobaPlot <- ggplot(LST8Discoba, aes(x = sca, y = scd, color = C.score, label = Organism_Name))+
  geom_point()+
  geom_text_repel(data = LST8Discoba,
                  direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("LST8 Hits Discoba")






RAPTORDiscobaPlot
RICTORMetamonadaPlot
RICTORDiscobaPlot
RICTORMetamonadaPlot
TORDiscobaPlot
TORMetamonadaPlot
SIN1DiscobaPlot
SIN1MetamonadaPlot
LST8DiscobaPlot
LST8MetamonadaPlot






















```


