---
title: "Streptophyta/Chlorophyta/Rhodophyta_Analysis"
author: "Kyle Johnson"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
# Only use if the packages have not been installed in this environment
# Packages 
 #install.packages("tidyverse")
 #install.packages("rentrez")
 #install.packages("gridExtra")
 #install.packages("plotly")
 #install.packages("kableExtra")
```




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Include the libraries here
# Libraries
library(tidyverse)
library(rentrez)
library(ggrepel)
library(gridExtra)
library(plotly)
library(kableExtra)


```





```{r setup, include=FALSE}
# Initalize the functions here
# Functions for filtering purposes and addition of information

Species_Name <- function(maincsv, namecsv){
  #First add the organism name column to the maincsv
  #Filling it with NA
  #Check to see if it has it already
  if ("Organism" %in% colnames(maincsv)){
  }else{
    maincsv <- maincsv %>% add_column(Organism=NA, .before = "tid")
  }
  #Iterate through the rows of the main csv file
  for (i in 1:nrow(maincsv)){
    #print(maincsv[i, "taxid"])
    
    #Iterate through the name csv file
    for (n in 1:nrow(namecsv)){
      if (maincsv[i, "taxid"] == namecsv[n, "Organism_Taxonomic_ID"]){
        #print(namecsv[n,"Organism"])
        maincsv$Organism[i] <- namecsv$Organism.Name[n]
      } else{
        next
      }
    }
  }
  return(maincsv) 
}

Taxon_Add <- function(csvToAdd){
  temp <- csvToAdd
  if("taxid" %in% colnames(temp)){
  }else{
    temp <- temp %>%
      add_column(taxid = NA, .before = "tar")
  }
    for (r in 1:nrow(temp)){
      print(r)
      targ <- temp[r, "tar"]
      eSearch <- entrez_search(db ="protein", term = targ)
      eSummary <- entrez_summary(db="protein", id=eSearch$ids)
      print(eSummary$taxid)
      if(is.null(eSummary$taxid)){
        next
      } else{}
      
      taxID <- extract_from_esummary(eSummary, "taxid")
      ID <- unname(taxID)
      if(nrow(temp) >0){
        temp$taxid[r] <- ID
      } else {}
    }
# Finally, return the value held within temp to the output of the function
  return(temp)
}

Check_Ciliates <- function (toBeCompared, ciliate){
  # Add in a column that will have values for comparing. Default is false
  # Adding the column after the Organism column (requires that it exists)
  if ("Ciliate_Check" %in% colnames(toBeCompared)){
  }else{
    toBeCompared <- toBeCompared %>%
      add_column(Ciliate_Check = FALSE, .after = "bid")
  }
  #print(toBeCompared)
  # Get rid of any spaces and replace them with _
  colnames(ciliate) = gsub(" ", "_", colnames(ciliate))
  #print(nrow(ciliate))
  #print(ciliate)
  
  # Iterate through the toBeCompared dataframe and the ciliates dataframe
  if(dim(toBeCompared)[1] == 0){
    return(toBeCompared)
  }else{
    for (n in 1:nrow(toBeCompared)){
      for(c in 1:nrow(ciliate)){
        if(toBeCompared[n, "Organism_Taxonomic_ID"] == ciliate[c, "Organism_Taxonomic_ID"]){
          toBeCompared$Ciliate_Check[n] <- TRUE
        }else{}
      }
  }
  return(toBeCompared)
  }
}

photoCheck <- function(inputCSV , photoCSV){
  if ("Has_D1" %in% colnames(inputCSV)){
  }else{
    inputCSV <- inputCSV %>% add_column(Has_D1 = FALSE, .after = "bid")
  }
  
  if(dim(inputCSV)[1] == 0){
    return(inputCSV)
  }else{
    for(n in 1:nrow(photoCSV)){
    #print("PhotoCSV Values")
    #print(photoCSV$Has_D1[n])
      for(m in 1:nrow(inputCSV)){
      #print("InputCSV Values")
      #print(inputCSV$Has_D1[m])
        if(inputCSV[m, "Organism_Taxonomic_ID"] == photoCSV[n,"Organism_Taxonomic_ID"]){
          inputCSV$Has_D1[m] <- TRUE
        }else{
        }
      }
    }
  #print(inputCSV$Has_D1)
    return(inputCSV)
  }
}

ComplexCheck2 <- function (inputdf, SIN1df, RICTORdf){
  # Check to see if the input function has the column already. Add it if it does not
  if ("TORC2" %in% colnames(inputdf)){
  }else{
    inputdf <- inputdf %>% add_column(TORC2 = FALSE, .after = "Organism.Name")
  }
  
  
  #Loop to iterate through the inputdf
  for (n in 1:nrow(inputdf)) {
    #Loop to iterate through the RICTORdf
    for (i in 1:nrow(RICTORdf)){
      #Loop to iterate through the SIN1df
      for (j in 1:nrow(SIN1df)){
        if (inputdf[n, "Organism_Taxonomic_ID"] == RICTORdf[i, "Organism_Taxonomic_ID"] & inputdf[n, "Organism_Taxonomic_ID"] == SIN1df[j, "Organism_Taxonomic_ID"]){
          inputdf$TORC2[n] <- TRUE
        }else{}
      }
    }
  }
  
  return(inputdf)
  
}

mainCombine <- function(Grouping, Namedf, RICTORdf, SIN1df, RAPTORdf, LST8df, TORdf, D1df){
  
  # Make the empty dataframe
  returnDf <- data.frame()
  
  # Add in the taxid and species names columns to the dataframe
  returnDF <- subset(Namedf, select = c("Accn","Organism_Taxonomic_ID", "Organism_Name"))
  
  # Now create empty columns and rows that will be filled in later in the function
  # These will be the "checking" sections for each of the specified proteins
  
  returnDF <- returnDF %>% add_column(SIN1 = NA, RICTOR = NA, RAPTOR = NA, TOR = NA, LST8 = NA, D1 = NA)
  returnDF <- returnDF %>% add_column(Phylum = Grouping, .before = "Accn")
  
  #Check the input dataframes to see if they are of length 0. If they are, do something about it
  
  
  if(nrow(RICTORdf) != 0){# First loop to check for RICTOR
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(RICTORdf)){
        #condition check to see if the taxIDs line up
        if(returnDF[n, "Organism_Taxonomic_ID"] == RICTORdf[m, "Organism_Taxonomic_ID"]){
          if (RICTORdf[m, "scd"] > 300){
          returnDF$RICTOR[n] <- "H"
          }else if (RICTORdf[m,"scd"] < 300 & RICTORdf[m,"scd"] > 150){
          returnDF$RICTOR[n] <- "M"
          }else if (RICTORdf[m,"scd"] < 150){
          returnDF$RICTOR[n] <- "L"
          }
        } else{
          next
        }
      }
      
    }
    print("Finished RICTOR")
  }else{}
    #Second Loop for SIN1
  if(nrow(SIN1df) != 0){
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(SIN1df)){
        #condition check to see if the taxIDs line up
        if(returnDF[n, "Organism_Taxonomic_ID"] == SIN1df[m, "Organism_Taxonomic_ID"]){
          if (SIN1df[m, "scd"] > 300){
          returnDF$SIN1[n] <- "H"
          }else if (SIN1df[m,"scd"] < 300 & SIN1df[m,"scd"] > 150){
          returnDF$SIN1[n] <- "M"
          }else if (SIN1df[m,"scd"] < 150){
          returnDF$SIN1[n] <- "L"
          }
        } else{
          next
        }
      }
      
    }
    print("Finished SIN1")
  }else{}

    #Third Loop for RAPTOR
  if(nrow(RAPTORdf) != 0){
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(RAPTORdf)){
        #condition check to see if the taxIDs line up
        if(returnDF[n, "Organism_Taxonomic_ID"] == RAPTORdf[m, "Organism_Taxonomic_ID"]){
          if (RAPTORdf[m, "scd"] > 300){
          returnDF$RAPTOR[n] <- "H"
          }else if (RAPTORdf[m,"scd"] < 300 & RAPTORdf[m,"scd"] > 150){
          returnDF$RAPTOR[n] <- "M"
          }else if (RAPTORdf[m,"scd"] < 150){
          returnDF$RAPTOR[n] <- "L"
          }
        } else{
          next
        }
      }
      
    }
    print("Finished RAPTOR")
  }else{}
  
  
    #Fourth Loop for LST8
  print(nrow(LST8df))
  if(nrow(LST8df) != 0){
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(LST8df)){
        #condition check to see if the taxIDs line up
        if(returnDF[n,"Organism_Taxonomic_ID"] == LST8df[m, "Organism_Taxonomic_ID"]){
          if (LST8df[m, "scd"] > 300){
          returnDF$LST8[n] <- "H"
          }else if (LST8df[m,"scd"] < 300 & LST8df[m,"scd"] > 150){
          returnDF$LST8[n] <- "M"
          }else if (LST8df[m,"scd"] < 150){
          returnDF$LST8[n] <- "L"
          }
        } else{
          next
        }
      }
    }
    print("Finished LST8")
  }else{}
  
    #Fourth Loop for TOR
  if(nrow(TORdf) != 0){
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(TORdf)){
        #condition check to see if the taxIDs line up
        if(returnDF[n, "Organism_Taxonomic_ID"] == TORdf[m, "Organism_Taxonomic_ID"]){
          if (TORdf[m, "scd"] > 300){
          returnDF$TOR[n] <- "H"
          }else if (TORdf[m,"scd"] < 300 & TORdf[m,"scd"] > 150){
          returnDF$TOR[n] <- "M"
          }else if (TORdf[m,"scd"] < 150){
          returnDF$TOR[n] <- "L"
          }
        } else{
          next
        }
      }
      
    }
  }else{}

  
      #Fifth Loop for D1
  if(nrow(D1df) != 0){
    for (n in 1:nrow(returnDF)){
      for (m in 1:nrow(D1df)){
        #condition check to see if the taxIDs line up
        if(returnDF[n, "Organism_Taxonomic_ID"] == D1df[m, "Organism_Taxonomic_ID"]){
          if (D1df[m, "scd"] > 300){
          returnDF$D1[n] <- "H"
          }else if (D1df[m,"scd"] < 300 & D1df[m,"scd"] > 150){
          returnDF$D1[n] <- "M"
          }else if (D1df[m,"scd"] < 150){
          returnDF$D1[n] <- "L"
          }
        } else{
          next
        }
      }
      
    } 
  }else{}
  
  
# Finally return the completed dataframe   
return(returnDF)  
}




# Global Variables for Analysis

# Score Values
#LST8, RAPTOR, TOR
LRTScoreA <- 150
LRTScoreD <- 150

#RICTOR, SIN1, D1
RSDScoreA <- 100
RSDScoreD <- 100
```

Reading in the Archaeplastida group here. This includes Streptophyta, Rhodophyta, Chlorophyta. This section is reading in the raw data for all of these groups.

```{r}

D1StreptophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Streptophyta/D1_Streptophyta.csv")
LST8StreptophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Streptophyta/LST8_Streptophyta.csv")
RICTORStreptophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Streptophyta/RICTOR_Streptophyta.csv")
RAPTORStreptophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Streptophyta/RAPTOR_Streptophyta.csv")
SIN1StreptophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Streptophyta/SIN1_Streptophyta.csv")
TORStreptophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Streptophyta/TOR_Streptophyta.csv")
StreptophytaNames <- read_tsv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Streptophyta/Streptophyta_Names.tsv", show_col_types = FALSE)
StreptophytaNames <- StreptophytaNames %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")

D1ChlorophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Chlorophyta/D1_Chlorophyta.csv")
LST8ChlorophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Chlorophyta/LST8_Chlorophyta.csv")
RICTORChlorophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Chlorophyta/RICTOR_Chlorophyta.csv")
RAPTORChlorophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Chlorophyta/RAPTOR_Chlorophyta.csv")
SIN1ChlorophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Chlorophyta/SIN1_Chlorophyta.csv")
TORChlorophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Chlorophyta/TOR_Chlorophyta.csv")
ChlorophytaNames <- read_tsv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Chlorophyta/Chlorophyta_Names.tsv", show_col_types = FALSE)
ChlorophytaNames <- ChlorophytaNames %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")

D1RhodophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Rhodophyta/D1_Rhodophyta.csv")
LST8RhodophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Rhodophyta/LST8_Rhodophyta.csv")
RICTORRhodophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Rhodophyta/RICTOR_Rhodophyta.csv")
RAPTORRhodophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Rhodophyta/RAPTOR_Rhodophyta.csv")
SIN1RhodophytaRaw <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Rhodophyta/SIN1_Rhodophyta.csv")
TORRhodophytaRaw  <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Rhodophyta/TOR_Rhodophyta.csv")
RhodophytaNames <- read_tsv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Rhodophyta/Rhodophyta_Names.tsv", show_col_types = FALSE)
RhodophytaNames <- RhodophytaNames %>% rename(Accn = "Assembly Accession") %>% rename(Organism_Taxonomic_ID = "Organism Taxonomic ID") %>% rename(Organism_Name = "Organism Name")
```


```{r}

FullTaxonomyStreptophyta <- read_tsv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Streptophyta/Streptophyta_taxonomy_summary.tsv", show_col_types = FALSE) %>% rename(Organism_Taxonomic_ID = "Taxid")

FullTaxonomyRhodophyta <- read_tsv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Rhodophyta/taxonomy_summary.tsv", show_col_types = FALSE) %>% rename(Organism_Taxonomic_ID = "Taxid")

FullTaxonomyChlorophyta <- read_tsv("~/Code/TOR_phylogenetics/GitHub_CSV/Updated_Chlorophyta/taxonomy_summary.tsv", show_col_types = FALSE) %>% rename(Organism_Taxonomic_ID = "Taxid")

```




```{r}

D1Streptophyta <- merge(D1StreptophytaRaw, StreptophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
LST8Streptophyta <- merge(LST8StreptophytaRaw, StreptophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
RAPTORStreptophyta <- merge(RAPTORStreptophytaRaw, StreptophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
RICTORStreptophyta <- merge(RICTORStreptophytaRaw, StreptophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
SIN1Streptophyta <- merge(SIN1StreptophytaRaw, StreptophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
TORStreptophyta <- merge(TORStreptophytaRaw, StreptophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")


D1Rhodophyta <- merge(D1RhodophytaRaw, RhodophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn") 
LST8Rhodophyta <- merge(LST8RhodophytaRaw, RhodophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
RAPTORRhodophyta <- merge(RAPTORRhodophytaRaw, RhodophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
RICTORRhodophyta <- merge(RICTORRhodophytaRaw, RhodophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
SIN1Rhodophyta <- merge(SIN1RhodophytaRaw, RhodophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
TORRhodophyta <- merge(TORRhodophytaRaw, RhodophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")

D1Chlorophyta <- merge(D1ChlorophytaRaw, ChlorophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
LST8Chlorophyta <- merge(LST8ChlorophytaRaw, ChlorophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
RAPTORChlorophyta <- merge(RAPTORChlorophytaRaw, ChlorophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
RICTORChlorophyta <- merge(RICTORChlorophytaRaw, ChlorophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
SIN1Chlorophyta <- merge(SIN1ChlorophytaRaw, ChlorophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")
TORChlorophyta <- merge(TORChlorophytaRaw, ChlorophytaNames[c("Organism_Taxonomic_ID", "Organism_Name", "Accn")], by ="Accn")




```

```{r}
# Picking the highest possible scd and evd value for each of the organisms
# Streptophyta Section
D1Streptophyta <- D1Streptophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
LST8Streptophyta <- LST8Streptophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
RAPTORStreptophyta <- RAPTORStreptophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
RICTORStreptophyta <- RICTORStreptophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
SIN1Streptophyta <- SIN1Streptophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
TORStreptophyta <- TORStreptophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
```


```{r}
# Rhodophyta Section
D1Rhodophyta <- D1Rhodophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
LST8Rhodophyta <- LST8Rhodophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
RAPTORRhodophyta <- RAPTORRhodophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
RICTORRhodophyta <- RICTORRhodophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
SIN1Rhodophyta <- SIN1Rhodophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
TORRhodophyta <- TORRhodophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
```


```{r}
# Chlorophyta Section
D1Chlorophyta <- D1Chlorophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
LST8Chlorophyta <- LST8Chlorophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
RAPTORChlorophyta <- RAPTORChlorophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
RICTORChlorophyta <- RICTORChlorophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
SIN1Chlorophyta <- SIN1Chlorophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup
TORChlorophyta <- TORChlorophyta %>% filter(sca >= 100 & scd >= 100)%>%
  group_by(Organism_Taxonomic_ID) %>%
  slice_max(scd) %>%
  slice_max(evd)%>%
  ungroup


```



```{r}
# Temp Code
# clipr::write_clip(RICTORChlorophyta$tar)
# write.table(D1Streptophyta$tar, "C:/Users/kajoh/Desktop/Batch_Prot.txt", sep = "\t", row.names = F, col.names = F, quote = F)


```


```{r}
# Busco scores will be added here to the different dfs
Rhodophyta_Busco <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Rhodophyta-BUSCO-Sheet1.csv", na = 0)
Rhodophyta_Busco <- Rhodophyta_Busco %>% rename(Accn = Accession)
Rhodophyta_Busco$C.score <-gsub("%$","",Rhodophyta_Busco$C.score)
Rhodophyta_Busco$C.score <- as.numeric(as.character(Rhodophyta_Busco$C.score))
Rhodophyta_Busco$Frag.score <- gsub("%$", "", Rhodophyta_Busco$Frag.score)
Rhodophyta_Busco$Frag.score <- as.numeric(as.character(Rhodophyta_Busco$Frag.score))

Chlorophyta_Busco <- read.csv("~/Code/TOR_phylogenetics/GitHub_CSV/Chlorophyta-BUSCO-Sheet1.csv", na = 0)
Chlorophyta_Busco <- Chlorophyta_Busco %>% rename(Accn = Accession)
Chlorophyta_Busco$C.score <-gsub("%$","",Chlorophyta_Busco$C.score)
Chlorophyta_Busco$C.score <- as.numeric(as.character(Chlorophyta_Busco$C.score))
Chlorophyta_Busco$Frag.score <- gsub("%$", "", Chlorophyta_Busco$Frag.score)
Chlorophyta_Busco$Frag.score <- as.numeric(as.character(Chlorophyta_Busco$Frag.score))

Streptophyta_Busco <- read.csv("~/Code/Tor_phylogenetics/GitHub_CSV/Streptophyta_Busco.csv")
Streptophyta_Busco$C.score <-gsub("%$","",Streptophyta_Busco$C.score)
Streptophyta_Busco$C.score <- as.numeric(as.character(Streptophyta_Busco$C.score))
Streptophyta_Busco$Frag.score <- gsub("%$", "", Streptophyta_Busco$Frag.score)
Streptophyta_Busco$Frag.score <- as.numeric(as.character(Streptophyta_Busco$Frag.score))
```


```{r}
CombinedStreptophyta <- mainCombine("Streptophyta", StreptophytaNames, RICTORStreptophyta, SIN1Streptophyta, RAPTORStreptophyta, LST8Streptophyta, TORStreptophyta, D1Streptophyta)
CombinedStreptophyta <- merge(CombinedStreptophyta, Streptophyta_Busco[c("C.score","Frag.score", "Accn")], by = "Accn")
```

```{r}
CombinedRhodophyta <- mainCombine("Rhodophyta", RhodophytaNames, RICTORRhodophyta, SIN1Rhodophyta, RAPTORRhodophyta, LST8Rhodophyta, TORRhodophyta, D1Rhodophyta)
CombinedRhodophyta <- merge(CombinedRhodophyta, Rhodophyta_Busco[c("C.score","Frag.score", "Accn")], by = "Accn")

CombinedChlorophyta <- mainCombine("Chlorophyta", ChlorophytaNames, RICTORChlorophyta, SIN1Chlorophyta, RAPTORChlorophyta, LST8Chlorophyta, TORChlorophyta, D1Chlorophyta)
CombinedChlorophyta <- merge(CombinedChlorophyta, Chlorophyta_Busco[c("C.score","Frag.score", "Accn")], by = "Accn")
```


```{r}
#CombinedStreptophyta <- CombinedStreptophyta %>% add_column(Class = NA, .after = "Group")
CombinedStreptophyta <- CombinedStreptophyta %>% left_join(select(FullTaxonomyStreptophyta, `Class name`,`Phylum name`,`Order name`, `Family name`, `Genus name`, Organism_Taxonomic_ID), by=c("Organism_Taxonomic_ID"))

CombinedRhodophyta <- merge(CombinedRhodophyta, Rhodophyta_Busco[c("C.score","Frag.score", "Accn")], by = "Accn")
CombinedRhodophyta <- CombinedRhodophyta %>% left_join(select(FullTaxonomyRhodophyta, `Class name`,`Phylum name`,`Order name`, `Family name`, `Genus name`, Organism_Taxonomic_ID), by=c("Organism_Taxonomic_ID"))

#Create a new column in the combined alveolata
CombinedChlorophyta <- merge(CombinedChlorophyta, Chlorophyta_Busco[c("C.score","Frag.score", "Accn")], by = "Accn")
CombinedChlorophyta <- CombinedChlorophyta %>% left_join(select(FullTaxonomyChlorophyta, `Class name`,`Phylum name`,`Order name`, `Family name`, `Genus name`, Organism_Taxonomic_ID), by=c("Organism_Taxonomic_ID"))



```

```{r}
write.csv(CombinedStreptophyta, file = "C:/Users/kajoh/Documents/Code/TOR_phylogenetics/GitHub_CSV/Combined_CSVs/Combined_Streptophyta.csv")
write.csv(CombinedChlorophyta, file = "C:/Users/kajoh/Documents/Code/TOR_phylogenetics/GitHub_CSV/Combined_CSVs/Combined_Chlorophyta.csv")
write.csv(CombinedRhodophyta, file = "C:/Users/kajoh/Documents/Code/TOR_phylogenetics/GitHub_CSV/Combined_CSVs/Combined_Rhodophyta.csv")
```




```{r}

RICTORStreptophytaPlot <- ggplot(RICTORStreptophyta, aes(x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 30,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("RICTOR Hits Streptophyta")
  
RICTORStreptophytaPlot

SIN1StreptophytaPlot <- ggplot(SIN1Streptophyta, aes(x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 30,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("SIN1 Hits Streptophyta")

SIN1StreptophytaPlot

RAPTORStreptophytaPlot <- ggplot(RAPTORStreptophyta, aes(x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 30,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("RAPTOR Hits Streptophyta")
RAPTORStreptophytaPlot

LST8StreptophytaPlot <- ggplot(LST8Streptophyta, aes(x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 30,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("LST8 Hits Streptophyta")
LST8StreptophytaPlot

TORStreptophytaPlot <- ggplot(TORStreptophyta, aes(x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 30,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("TOR Hits Streptophyta")
TORStreptophytaPlot



```

```{r}
# Chlorophyta RICTOR Search

RICTORChlorophytaPlot <- ggplot(RICTORChlorophyta, aes( x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 30,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("RICTOR Hits Chlorophyta")
RICTORChlorophytaPlot

RAPTORChlorophytaPlot <- ggplot(RAPTORChlorophyta, aes(x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("RAPTOR Hits Chlorophyta")
RAPTORChlorophytaPlot

SIN1ChlorophytaPlot <- ggplot(SIN1Chlorophyta, aes(x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("SIN1 Hits Chlorophyta")
SIN1ChlorophytaPlot

LST8ChlorophytaPlot <- ggplot(LST8Chlorophyta, aes(x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("LST8 Hits Chlorophyta")
LST8ChlorophytaPlot

TORChlorophytaPlot <- ggplot(TORChlorophyta, aes(x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 10,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("RAPTOR Hits Chlorophyta")
TORChlorophytaPlot
  
```

```{r}
RAPTORRodophytaPlot <- ggplot(RAPTORRhodophyta, aes( x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 30,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("RAPTOR Hits Rhodophyta")
RAPTORRodophytaPlot

LST8RhodophytaPlot <- ggplot(LST8Rhodophyta, aes( x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 30,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("LST8 Hits Rhodophyta")
LST8RhodophytaPlot

TORRhodophytaPlot <- ggplot(TORRhodophyta, aes( x = sca, y = scd, label = Organism_Name))+
  geom_point()+
  geom_text_repel(direction = "y",
                  min.segment.length = 0.5,
                  force = 10,
                  max.time = 10,
                  max.overlaps = 30,
                  nudge_x = -50,
                  nudge_y = .1,
                  point.padding = 0.6,
                  color = "black",
                  size = 2.0)+
  xlab("Overall Score of HMMER Hit")+
  ylab("Best Domain Score of HMMER Hit")+
  ggtitle("TOR Hits Rhodophyta")
TORRhodophytaPlot

```

