# Photosynthesis trees and overall metabolism
# Kyle Johnson
# 4/3/2025

# Load in the master table

MasterTable <- read.csv(file = "~/GitHub/TOR_phylogenetics/GitHub_CSV/Finalized_CSVs/Master_Table.csv")
MasterTable <- select(MasterTable, -X)

MasterTable %>% ggplot(aes(x = factor(RICTOR,level = c("H", "M", "L")), y = RICTORDomain, color = M.Strategy, size = C.score))+
  geom_jitter()+
  labs(title = "RICTOR Domain Score Distribution")+
  xlab(label = "RICTOR H/M/L")+
  ylab(label = "RICTOR Domain Scores")+
  #geom_text_repel(aes(label = Organism.Name), size = 2.2, show.legend = FALSE)+
  facet_wrap(~Super.Group,nrow = 1)





















# Random Assortment of truncations for truncated trees to be generated from NCBI Common Tree
# Can use the trees generated by these IDs in the main Tree_Plot_script
# 

StramSubset <- MasterTable %>% filter(Super.Group == "Stramenopiles")
StramSubset <- StramSubset %>%
  filter(Organism.Name != "Phytophthora citrophthora",
         Organism.Name != "Aphanomyces stellatus",
         Organism.Name != "Minidiscus trioculatus",
         Organism.Name != "Labyrinthula sp. Ha",
         Organism.Name != "Cafeteria roenbergensis",
         Organism.Name != "Phytophthora fragariaefolia",
         Organism.Name != "Phytophthora lilii",
         Organism.Name != "Peronosclerospora sorghi",
         Organism.Name != "Nothophytophthora sp. Chile5",
         Organism.Name != "Ochromonadaceae sp. CCMP2298")
  

AlvSubset <- MasterTable %>% filter(Super.Group == "Alveolata")
AlvSubset <- AlvSubset %>% filter(Organism.Name != "Moneuplotes crassus",
                                  Organism.Name != "Symbiodinium pilosum",
                                  Organism.Name != "Symbiodinium sp. CCMP2456",
                                  Organism.Name != "Symbiodinium necroappetens",
                                  Organism.Name != "Eimeria mitis",
                                  Organism.Name != "Eimeria necatrix",
                                  Organism.Name != "Eimeria praecox"
                                  )
  

RhizSubset <- MasterTable %>% filter(Super.Group == "Rhizaria")
RhizSubset <- RhizSubset %>% filter(Organism.Name != "Marteilia pararefringens",
                                    Organism.Name != "Paramarteilia canceri",
                                    Organism.Name != "Cercozoa sp. M6MM")

ExcSubset <- MasterTable %>% filter(Super.Group == "Discoba" | Super.Group == "Metamonada")
ExcSubset <- ExcSubset %>% filter(Organism.Name != "Trypanosoma brucei equiperdum",
                                  Organism.Name != "Trpanosoma equiperdum",
                                  Organism.Name != "Trypanosoma rangeli",
                                  Organism.Name != "Trypanosoma rangeli SC58",
                                  Organism.Name != "Strigomonas culicis",
                                  Organism.Name != "Perkinsela sp. CCAP 1560/4",
                                  Organism.Name != "Giardia lamblia ATCC 50803",
                                  Organism.Name != "Spironucleus salmonicida",
                                  Organism.Name != "Hexamita inflata",
                                  Organism.Name != "Streblomastix strix",
                                  Organism.Name != "Aduncisulcus paluster",
                                  Organism.Name != "Monocercomonoides exilis",
                                  Organism.Name != "Paratrimastix pyriformis",
                                  Organism.Name != "Novymonas esmeraldas")


ARSubset <- rbind(AlvSubset,RhizSubset)


write.table(StramSubset$Organism_Taxonomic_ID, file = "~/GitHub/TOR_phylogenetics/IDs/TruncatedStram.txt", sep = "\t", row.names = F, col.names = F)
write.table(AlvSubset$Organism_Taxonomic_ID, file = "~/GitHub/TOR_phylogenetics/IDs/TruncatedAlv.txt", sep = "\t", row.names = F, col.names = F)
write.table(ARSubset$Organism_Taxonomic_ID, file = "~/GitHub/TOR_phylogenetics/IDs/TruncatedAR.txt", sep = "\t", row.names = F, col.names = F)
write.table(ExcSubset$Organism_Taxonomic_ID, file = "~/GitHub/TOR_phylogenetics/IDs/TruncatedExc.txt", sep = "\t", row.names = F, col.names = F)

#Palettes-----------------------------------------------------------------------
pal <- c(
  "H" = "#7e2323",
  "M" = "#d0771a",
  "L" = "#ffc30b",
  "P" = "#7dbe62",
  "NA" = "#FF000000"
)
pal2 <- c(
  "H" = "#f4931f",
  "M" = "#f5da5f",
  "L" = "#41ad49",
  "P" = "#027aa4",
  "NA" = "#FF000000"
)
pal3 <- c(
  "H" = "#ae5a41",
  "P" = "#DBC795",
  "M" = "#559e83",
  "L" = "#B2D4AD",
  na_value = "#FF000000"
)

pal4 <- c(
  "H" = "#f4649e",
  "M" = "#49e5aa",
  "L" = "#d2ebfb",
  "P" = "#f0d14f",
  "NA" = "#FF000000"
)

Mpal <- c(
  "Autotrophic" = "green",
  "Heterotroph" = "brown",
  "Mixotroph" = "#7dbe62",
  "Parasite" = "red"
)

Mpal2 <- c(
  "Autotrophic" = "#3CBA26",
  "Heterotroph" = "#A87142",
  "Mixotroph" = "#63E3C5",
  "Parasite" = "#FE4A49" 
)


EMpal2 <- c(
  "Autotrophic" = "#3CBA26",
  "Endosymbiotic" = "purple",
  "Heterotroph" = "#A87142",
  "Mixotroph" = "#63E3C5",
  "Parasite" = "#FE4A49" 
)

#Tomato
#FE4A49

#Copper
#A87142


#Turquoise
#63E3C5

#Kelly Green
#3CBA26

#Agreed on using Pal3 for heat maps going forward













#Stramenopile Tree -------------------------------------------------------------

#Dataframe setup for Stramenopile Tree
#Establish the Stramenopiles Subsection
Stramenopiles <- MasterTable %>% filter(Super.Group == "Stramenopiles")
Stramenopiles <- Stramenopiles %>% relocate(Organism.Name)

#Make a subsection of the above dataframe and select only the values in SIN1, RICTOR, RAPTOR, LST8, and TOR.
#Move the Organism.Name column to the front to align it with the tree object
subsetdataframe <- Stramenopiles %>% select(Organism.Name, SIN1, RICTOR, RAPTOR, LST8,TOR) %>% distinct(Organism.Name, .keep_all = TRUE)
df <- column_to_rownames(subsetdataframe, var = "Organism.Name")

#Create the metabolic subset of the Stramenopiles Subsection
Msubset <- Stramenopiles %>% select(Organism.Name, M.Strategy)%>% distinct(Organism.Name, .keep_all = TRUE)
mdf <- column_to_rownames(Msubset, var = "Organism.Name")


#Read in the tree file for stramenopiles (truncated here).
#Remove any ' marks and replace them with white space
StramenopileTree <- read.tree(file = "~/GitHub/TOR_phylogenetics/Trees/TruncatedStramTreeP.phy")
StramenopileTree$tip.label <- gsub("'","", StramenopileTree$tip.label)


#Create the ggtree object using the Stramenopile tree
#Attach the Stramenopile Subsection dataframe to the tree for additional information
STP <- ggtree(StramenopileTree, branch.length = "none", ladderize = FALSE)
STP <- STP  %<+% Stramenopiles

#Create the first layer of the heatmap tree
#This layer is the C.score heatmap along with the tip labels
StramLayer1 <- STP + xlim(NA, +25) + geom_tiplab(size = 1.8, nudge_x = .3, linesize = .4, align = TRUE, aes(color=C.score), continuous = 'colour')+
  scale_color_gradientn(colours=c("#B88100", "#3083DC","#D71D36"),
                        guide = guide_colorbar(order =1),
                        name = "Completeness Score")+
  geom_rootedge()+
  labs(title = "Stramenopiles Phylogenetic Tree",
       subtitle = "With HMMER Score Map")

#Create the second layer of the heatmap tree
#This layer is the first heatmap which is the H,M,L,P values
#This takes in the df object which contains the relevant information
#This layer also specifies that it has a unique scale_fill
StramLayer2 <- gheatmap(StramLayer1, df, offset = 6.5, width = .65, font.size = 2, colnames = FALSE)+
  scale_fill_manual(name = "HMMER Score",
                    breaks = c("H","M","L","P",NA),
                    values = pal3,
                    limits = c("H","M","L","P", NA),
                    na.value = "#FFFFFF",
                    drop = FALSE)+
  theme(
    text = element_text(family = "serif"),
    legend.background=element_rect(fill=NA),
    legend.title=element_text(size=10), 
    legend.text=element_text(size=5.5),
    legend.spacing.y = unit(0.02, "cm"),
    legend.key.spacing.x = unit(1,"cm"))+
  new_scale_fill()

#Create the third layer of the heatmap tree
#This layer is the second heatmap which is the Metabolic Strategies
#This takes in the mdf object which has the metabolic information
StramLayer3 <- gheatmap(StramLayer2,mdf, offset = 12, width = .15, colnames = FALSE)+
  scale_fill_manual(name = "Metabolic Strategy",
                    breaks = c("Autotrophic","Heterotroph","Mixotroph","Parasite"),
                    values = Mpal2,
                    limits = c("Autotrophic", "Heterotroph", "Mixotroph", "Parasite"),
                    drop = FALSE)+
  theme(
    text = element_text(family = "serif"),
    legend.background=element_rect(fill=NA),
    legend.title=element_text(size=10), 
    legend.text=element_text(size=5.5),
    legend.spacing.y = unit(0.02, "cm"),
    legend.key.spacing.x = unit(1,"cm"))+
  new_scale_fill()

#Finally we have a completed heatmap image for Stramenopiles
#We can then save the image to either a png or a pptx file format here

StramLayer3

ggsave("~/GitHub/TOR_phylogenetics/Images/Updated_Tree_Images/PrototypeHeatMapStramenopileTruncated.png",
       plot = StramLayer3,
       width = 3840,
       height = 2160,
       units = "px",
       dpi = 320,
       limitsize = FALSE)




























#Alveolata ---------------------------------------------------------------------

#Dataframe setup for Alveolata Tree
#Establish the Alveolata Subsection
#Follows an exact procedure to the Stramenopiles Section
Alveolata <- MasterTable %>% filter(Super.Group == "Alveolata")
Alveolata <- Alveolata %>% relocate(Organism.Name)

subsetdataframe <- Alveolata %>% select(Organism.Name, SIN1, RICTOR, RAPTOR, LST8,TOR) %>% distinct(Organism.Name, .keep_all = TRUE)
df <- column_to_rownames(subsetdataframe, var = "Organism.Name")

Msubset <- Alveolata %>% select(Organism.Name, M.Strategy)%>% distinct(Organism.Name, .keep_all = TRUE)
mdf <- column_to_rownames(Msubset, var = "Organism.Name")

#Load in the tree data
#Clean up the tip labels
AlveolataTree <- read.tree(file = "~/Github/TOR_phylogenetics/Trees/TruncatedAlvTreeP.phy")
AlveolataTree$tip.label <- gsub("'","", AlveolataTree$tip.label)

AlveolataTree <- move.lineage(AlveolataTree, 135, 169, rescale = TRUE)
AlveolataTree <- move.lineage(AlveolataTree, 134, 142, rescale = TRUE)
AlveolataTree <- move.lineage(AlveolataTree, 169, 141, rescale = TRUE)


#Create ggtree object
AlvP <- ggtree(AlveolataTree, branch.length = "none", ladderize = FALSE)
AlvP <- AlvP  %<+% Alveolata
AlvP + geom_text(aes(label = node))+geom_tiplab()+geom_nodelab()

#Alv Layer 1
AlvLayer1 <- AlvP + xlim(NA,+20) + geom_tiplab(size = 1.8, show.legend = TRUE, nudge_x = .3, linesize = .2, align = TRUE, aes(color=C.score), continuous = 'colour')+
  scale_color_gradientn(colours=c("#B88100", "#3083DC","#D71D36"),
                        guide = guide_colorbar(order =1),
                        name = "Completeness Score")+
  geom_rootedge()+
  #geom_nodelab(nudge_y = 1.2, nudge_x = -.7, size = 1.5)+
  labs(title = "Alveolata Phylogenetic Tree",
       subtitle = "With HMMER Score Map")

#Alv Layer 2
AlvLayer2 <- gheatmap(AlvLayer1, df, offset = 4, font.size = 2,, width = .4, colnames = FALSE)+
  scale_fill_manual(name = "HMMER Score",
                    breaks = c("H","M","L","P",NA),
                    values = pal3,
                    limits = c("H","M","L","P", NA),
                    na.value = "#FFFFFF",
                    drop = FALSE)+
  theme(
    text = element_text(family = "serif"),
    legend.background=element_rect(fill=NA),
    legend.title=element_text(size=10), 
    legend.text=element_text(size=5.5),
    legend.spacing.y = unit(0.02, "cm"),
    legend.key.spacing.x = unit(1,"cm"))+
  new_scale_fill()

#Alv Layer 3
AlvLayer3 <- gheatmap(AlvLayer2,mdf, offset = 7, width = .15, colnames = FALSE)+
  scale_fill_manual(name = "Metabolic Strategy",
                    breaks = c("Autotrophic","Heterotroph","Mixotroph","Parasite"),
                    values = Mpal2,
                    limits = c("Autotrophic", "Heterotroph", "Mixotroph", "Parasite"),
                    drop = FALSE)+
  theme(
    text = element_text(family = "serif"),
    legend.background=element_rect(fill=NA),
    legend.title=element_text(size=10), 
    legend.text=element_text(size=5.5),
    legend.spacing.y = unit(0.02, "cm"),
    legend.key.spacing.x = unit(1,"cm"))+
  new_scale_fill()



AlvLayer3


ggsave("~/GitHub/TOR_phylogenetics/Images/Updated_Tree_Images/PrototypeHeatMapAlveolataTruncated.png",
       plot = AlvLayer3,
       width = 3840,
       height = 2160,
       units = "px",
       dpi = 320,
       limitsize = FALSE)




























# Excavata Combined Tree -------------------------------------------------------

ExcavataTree <- read.tree(file = "~/Github/TOR_phylogenetics/Trees/TruncatedExcTreeP.phy")
ExcavataTree$tip.label <- gsub("'","", ExcavataTree$tip.label)

Excavata <- MasterTable %>% filter(Super.Group == "Discoba" | Super.Group == "Metamonada")
Excavata <- Excavata %>% relocate(Organism.Name)

subsetdataframe3 <- Excavata %>% select(Organism.Name, 
                                         SIN1, 
                                         RICTOR, 
                                         RAPTOR, 
                                         LST8,
                                         TOR) %>% 
  distinct(Organism.Name, .keep_all = TRUE)
df3 <- column_to_rownames(subsetdataframe3, var = "Organism.Name")
Msubset2 <- Excavata %>% select(Organism.Name, M.Strategy)%>% distinct(Organism.Name, .keep_all = TRUE) #%>%
# pivot_longer(cols = !Organism.Name, names_to = "M.Strategy", values_to = "Type")
mdf2 <- column_to_rownames(Msubset2, var = "Organism.Name")




ExcavataTP <- ggtree(ExcavataTree, branch.length = "none", ladderize = FALSE)
ExcavataTP <- ExcavataTP  %<+% Excavata




ExcavataHeat <- ExcavataTree %>% ggtree(branch.length = "none", ladderize = FALSE)+xlim(NA,40)

ExcavataHeatPlot <- gheatmap(ExcavataHeat,df3, offset = 7, width = .8, font.size = 2, colnames = FALSE)+
  scale_fill_manual(name = "HMMER Score",
                    breaks = c("H","M","L","P",NA),
                    values = pal3,
                    limits = c("H","M","L","P", NA),
                    na.value = "#FFFFFF",
                    drop = FALSE)+
  theme(
    text = element_text(family = "serif"),
    legend.background=element_rect(fill=NA),
    legend.title=element_text(size=10), 
    legend.text=element_text(size=5.5),
    legend.spacing.y = unit(0.02, "cm"),
    legend.key.spacing.x = unit(1,"cm"))+
  new_scale_fill()




ExcavataSavePlot <- ExcavataHeatPlot %<+% Excavata+geom_tiplab(size = 1.8, nudge_x = .3, linesize = .4, align = TRUE, aes(color=C.score), continuous = 'colour')+
  scale_color_gradientn(colours=c("#B88100", "#3083DC","#D71D36"),
                        guide = guide_colorbar(order =1),
                        name = "Completeness Score")+
  # geom_cladelab(node=106, label="Heterotrophic", align = FALSE, geom = 'label',offset=2.5,barsize = 3)+
  # geom_cladelab(node=2, label="Filter-Feeder", align = FALSE, geom = 'label',offset=2.5,barsize = 3)+
  # geom_cladelab(node=92, label="Parasite", align = FALSE, geom = 'label',offset=3,barsize = 3)+
  # geom_cladelab(node=116, label="Autotrophic", align = FALSE, geom = 'label',offset=3,barsize = 3)+
  # geom_cladelab(node=111, label="Autotrophic", align = FALSE, geom = 'label',offset=3,barsize = 3)+
  # geom_cladelab(node=94, label="Heterotrophic", align = FALSE, geom = 'label',offset=3,barsize = 3)+
  geom_rootedge()+
  labs(title = "Excavates Phylogenetic Tree",
       subtitle = "With HMMER Score Map")

experimentalExcplot <- gheatmap(ExcavataSavePlot,mdf2, offset = 15.5, width = .15, colnames = FALSE)+
  scale_fill_manual(name = "Metabolic Strategy",
                    breaks = c("Autotrophic","Heterotroph","Mixotroph","Parasite", "Endosymbiote"),
                    values = EMpal2,
                    limits = c("Autotrophic", "Heterotroph", "Mixotroph", "Parasite", "Endosymbiote"),
                    na.value = "grey",
                    drop = FALSE)+
  theme(
    text = element_text(family = "serif"),
    legend.background=element_rect(fill=NA),
    legend.title=element_text(size=10), 
    legend.text=element_text(size=5.5),
    legend.spacing.y = unit(0.02, "cm"),
    legend.key.spacing.x = unit(1,"cm"))+
  new_scale_fill()
experimentalExcplot



ggsave("~/GitHub/TOR_phylogenetics/Images/Updated_Tree_Images/HeatMapExcavates.png",
       plot = ExcavataSavePlot,
       width = 3840,
       height = 2160,
       units = "px",
       dpi = 320,
       limitsize = FALSE)
ggsave("~/GitHub/TOR_phylogenetics/Images/Updated_Tree_Images/PrototypeExcMetHeat.png",
       plot = experimentalExcplot,
       width = 3840,
       height = 2160,
       units = "px",
       dpi = 320,
       limitsize = FALSE)



# Experimental -----------------------------------------------------------------
ARTree <- read.tree(file = "~/Github/TOR_phylogenetics/Trees/TruncatedARTreeP.phy")
ARTree$tip.label <- gsub("'","", ARTree$tip.label)

AR <- MasterTable %>% filter(Super.Group == "Alveolata" | Super.Group == "Rhizaria")
AR <- AR %>% relocate(Organism.Name)



ARTree <- move.lineage(ARTree, 138, 146)
ARTree <- move.lineage(ARTree, 138, 173)
ARTree <- move.lineage(ARTree, 172, 144)
ARTree <- move.lineage(ARTree, 146, 145)

subsetdataframe4 <- AR %>% select(Organism.Name, 
                                        SIN1, 
                                        RICTOR, 
                                        RAPTOR, 
                                        LST8,
                                        TOR) %>% 
  distinct(Organism.Name, .keep_all = TRUE)
df4 <- column_to_rownames(subsetdataframe4, var = "Organism.Name")

Msubset1 <- AR %>% select(Organism.Name, M.Strategy)%>% distinct(Organism.Name, .keep_all = TRUE) #%>%
# pivot_longer(cols = !Organism.Name, names_to = "M.Strategy", values_to = "Type")
mdf1 <- column_to_rownames(Msubset1, var = "Organism.Name")




ARTP <- ggtree(ARTree, branch.length = "none", ladderize = FALSE)
ARTP <- ARTP  %<+% AR
ARTP+geom_tiplab2()+geom_text(aes(label=node))


ARHeat <- ARTree %>% ggtree(branch.length = "none", ladderize = FALSE)+xlim(NA,30)
ARHeatPlot <- gheatmap(ARHeat,df4, offset = 6, width = .6, font.size = 2, colnames = FALSE)+
  scale_fill_manual(name = "HMMER Score",
                    breaks = c("H","M","L","P",NA),
                    values = pal3,
                    limits = c("H","M","L","P", NA),
                    na.value = "#FFFFFF",
                    drop = FALSE)+
  theme(
    text = element_text(family = "serif"),
    legend.background=element_rect(fill=NA),
    legend.title=element_text(size=10), 
    legend.text=element_text(size=5.5),
    legend.spacing.y = unit(0.02, "cm"),
    legend.key.spacing.x = unit(1,"cm"))+
  new_scale_fill()

ARHeatPlot

ARSavePlot <- ARHeatPlot %<+% AR+geom_tiplab(size = 1.8, nudge_x = .3, linesize = .4, align = TRUE, aes(color=C.score), continuous = 'colour')+
  scale_color_gradientn(colours=c("#B88100", "#3083DC","#D71D36"),
                        guide = guide_colorbar(order =1),
                        name = "Completeness Score")+
  geom_rootedge()+
  labs(title = "Alveolata and Rhizaria Phylogenetic Tree",
       subtitle = "With HMMER Score Map")

ARSavePlot

experimentalARplot <- gheatmap(ARSavePlot,mdf1, offset = 12, width = .15, colnames = FALSE)+
  scale_fill_manual(name = "Metabolic Strategy",
                    breaks = c("Autotrophic","Heterotroph","Mixotroph","Parasite", "Endosymbiotic"),
                    values = EMpal2,
                    limits = c("Autotrophic", "Heterotroph", "Mixotroph", "Parasite", "Endosymbiotic"),
                    na.value = "grey",
                    drop = FALSE)+
  theme(
    text = element_text(family = "serif"),
    legend.background=element_rect(fill=NA),
    legend.title=element_text(size=10), 
    legend.text=element_text(size=5.5),
    legend.spacing.y = unit(0.02, "cm"),
    legend.key.spacing.x = unit(1,"cm"))+
  new_scale_fill()
experimentalARplot

#Replace these Comment blocks if we switch back to the non-truncated tree


# AnnotatedARPlot1 <- viewClade(experimentalARplot, MRCA(experimentalARplot, "Amoebophrya sp. A120", "Symbiodinium microadriaticum"))
# AnnotatedARPlot1
# ggsave("~/GitHub/TOR_phylogenetics/Images/Updated_Tree_Images/HeatMapAlveolataRhizariaSymbiodinium.png",
#        plot = AnnotatedARPlot1,
#        width = 3840,
#        height = 2160,
#        units = "px",
#        dpi = 320,
#        limitsize = FALSE)





# AnnotatedARPlot2 <- viewClade(experimentalARplot, MRCA(experimentalARplot, "Cardiosporidium cionae", "Eimeria acervulina"))
# AnnotatedARPlot2
# ggsave("~/GitHub/TOR_phylogenetics/Images/Updated_Tree_Images/HeatMapAlveolataRhizariaParasites.png",
#        plot = AnnotatedARPlot2,
#        width = 3840,
#        height = 2160,
#        units = "px",
#        dpi = 320,
#        limitsize = FALSE)


ggsave("~/GitHub/TOR_phylogenetics/Images/Updated_Tree_Images/HeatMapAlveolataRhizaria.png",
       plot = ARSavePlot,
       width = 3840,
       height = 2160,
       units = "px",
       dpi = 320,
       limitsize = FALSE)

ggsave("~/GitHub/TOR_phylogenetics/Images/Updated_Tree_Images/PrototypeARMetHeatPlot.png",
       plot = experimentalARplot,
       width = 3840,
       height = 2160,
       units = "px",
       dpi = 320,
       limitsize = FALSE)



# SAR --------------------------------------------------------------------------

# Modify this tree to instead be a C.score filtered Tree
# Only do this for Alveolata and for Stramenopiles


SARTree <- read.tree(file = "~/Github/TOR_phylogenetics/Trees/SARTreeP.phy")
SARTree$tip.label
SARTree$tip.label <- gsub("'","", SARTree$tip.label)
SARTree$tip.label


SAR <- MasterTable %>% filter(Super.Group == "Alveolata" | Super.Group == "Rhizaria" | Super.Group == "Stramenopiles")
SAR <- SAR %>% relocate(Organism.Name)

subsetdataframe5 <- SAR %>% select(Organism.Name, 
                                  SIN1, 
                                  RICTOR, 
                                  RAPTOR, 
                                  LST8,
                                  TOR) %>% 
  distinct(Organism.Name, .keep_all = TRUE)
df5 <- column_to_rownames(subsetdataframe5, var = "Organism.Name")


SARHeat <- SARTree %>% ggtree(ladderize = FALSE, branch.length = "none", layout = "fan", open.angle = 180)+geom_rootedge()
SARHeat



SARHeatPlot <- gheatmap(SARHeat,df5, offset = 5, width = .8, font.size = 2, colnames = FALSE)+
  scale_fill_manual(name = "HMMER Score",
                    breaks = c("H","M","L","P",NA),
                    values = pal3,
                    limits = c("H","M","L","P", NA),
                    na.value = "#FFFFFF",
                    drop = FALSE)+
  theme(
    text = element_text(family = "serif"),
    legend.background=element_rect(fill=NA),
    legend.title=element_text(size=10), 
    legend.text=element_text(size=5.5),
    legend.spacing.y = unit(0.02, "cm"),
    legend.key.spacing.x = unit(1,"cm"))
SARHeatPlot


SARSavePlot <- SARHeatPlot %<+% SAR+geom_tiplab(size = 1.8, nudge_x = .3, linesize = .4, align = TRUE, aes(color=C.score), continuous = 'colour')+
  scale_color_gradientn(colours=c("#B88100", "#3083DC","#D71D36"),
                        guide = guide_colorbar(order =1),
                        name = "Completeness Score")+
  # geom_cladelab(node=106, label="Heterotrophic", align = FALSE, geom = 'label',offset=2.5,barsize = 3)+
  # geom_cladelab(node=2, label="Filter-Feeder", align = FALSE, geom = 'label',offset=2.5,barsize = 3)+
  # geom_cladelab(node=92, label="Parasite", align = FALSE, geom = 'label',offset=3,barsize = 3)+
  # geom_cladelab(node=116, label="Autotrophic", align = FALSE, geom = 'label',offset=3,barsize = 3)+
  # geom_cladelab(node=111, label="Autotrophic", align = FALSE, geom = 'label',offset=3,barsize = 3)+
  # geom_cladelab(node=94, label="Heterotrophic", align = FALSE, geom = 'label',offset=3,barsize = 3)+
  geom_rootedge()+
  labs(title = "SAR Phylogenetic Tree",
       subtitle = "With HMMER Score Map")

SARSavePlot







tempdataframe <- SAR
tempdataframe <- tempdataframe %>% mutate(NodeNumber = case_when(
                                                                 Super.Group == "Alveolata" ~ which(SARTree$node.label == "Alveolata") + length(SARTree$tip.label),
                                                                 Super.Group == "Stramenopiles" ~ which(SARTree$node.label == "Stramenopiles") + length(SARTree$tip.label),
                                                                 Super.Group == "Rhizaria" ~ which(SARTree$node.label == "Rhizaria") + length(SARTree$tip.label)))%>%
select(NodeNumber, Super.Group) %>% distinct(Super.Group, .keep_all = TRUE)








testSIN1Data <- SAR %>% select(Organism.Name, SIN1)%>%
  pivot_longer(cols = !Organism.Name,names_to = "Protein", values_to = "Score")

testRICTORData <- SAR %>% select(Organism.Name, RICTOR)%>%
  pivot_longer(cols = !Organism.Name,names_to = "Protein", values_to = "Score")

testRAPTORData <- SAR %>% select(Organism.Name, RAPTOR)%>%
  pivot_longer(cols = !Organism.Name,names_to = "Protein", values_to = "Score")

testLST8Data <- SAR %>% select(Organism.Name, LST8)%>%
  pivot_longer(cols = !Organism.Name,names_to = "Protein", values_to = "Score")

testTORData <- SAR %>% select(Organism.Name, TOR)%>%
  pivot_longer(cols = !Organism.Name,names_to = "Protein", values_to = "Score")

testAllTree <- SARHeat +
  geom_highlight(data = tempdataframe,
                 mapping = aes(node = NodeNumber, fill = Super.Group))+
  scale_fill_manual(name = "Super Group",
                    breaks = c("Alveolata","Stramenopiles","Rhizaria"),
                    values = c("Alveolata" = "#EFB911",
                               "Stramenopiles" = "#572100",
                               "Rhizaria" = "#FFD0AB"
                    ))+
  geom_rootedge()+
  new_scale_fill()+
  geom_fruit(data = testSIN1Data,
             geom = geom_tile,
             mapping = aes(x = Protein, y = Organism.Name, fill = Score),width = .5, offset = 0.04)+
  geom_fruit(data = testRICTORData,
             geom = geom_tile,
             mapping = aes(x = Protein, y = Organism.Name, fill = Score), width = .5, offset = 0.04)+
  geom_fruit(data = testRAPTORData,
             geom = geom_tile,
             mapping = aes(x = Protein, y = Organism.Name, fill = Score), width = .5, offset = 0.04)+
  geom_fruit(data = testLST8Data,
             geom = geom_tile,
             mapping = aes(x = Protein, y = Organism.Name, fill = Score), width = .5, offset = 0.04)+
  geom_fruit(data = testTORData,
             geom = geom_tile,
             mapping = aes(x = Protein, y = Organism.Name, fill = Score), width = .5, offset =0.04)+
  scale_fill_manual(name = "HMMER Score",
                    breaks = c("H","M","L","P","NA"),
                    values = pal3,
                    limits = c("H","M","L","P", "NA"),
                    na.value = "#FF000000",
                    drop = FALSE)+
  theme(
    legend.background=element_rect(fill=NA),
    legend.title=element_text(size=10), 
    legend.text=element_text(size=5.5),
    legend.spacing.y = unit(0.02, "cm"),
    legend.key.spacing.x = unit(1,"cm"))+
  hexpand(.5, direction = -1)+
  vexpand(1, direction = -1)

testAllTree



ggsave("~/GitHub/TOR_phylogenetics/Images/Updated_Tree_Images/HeatMapSAR.png",
       plot = testAllTree,
       width = 3840,
       height = 2160,
       units = "px",
       dpi = 320,
       limitsize = FALSE)














BoxPlotCscore <- MasterTable %>% ggplot()+
  stat_boxplot(aes(Super.Group, C.score), geom = "errorbar", linetype = 1, width = 0.5)+
  geom_boxplot(aes( x = Super.Group, y = C.score),notch = FALSE, outlier.shape = NA)+
  theme_bw()+
  labs(title = "Completeness Score Distribution",
       subtitle = "By Associated Super Group")+
  xlab(label = "Super Group")+
  ylab(label = "Completeness Score")




ggsave("~/GitHub/TOR_phylogenetics/Images/Updated_Figure_Images/CscorePlot.png",
       plot = BoxPlotCscore,
       width = 3840,
       height = 2160,
       units = "px",
       dpi = 320,
       limitsize = FALSE)

